include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    type_literal_in_constant_pattern: ignore
  exclude:
    - "**/*.g.dart"

linter:

  rules:
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    curly_braces_in_flow_control_structures: true
    discarded_futures: true
    empty_catches: true
    file_names: true
    join_return_with_assignment: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas : true
    unnecessary_await_in_return: true
    use_build_context_synchronously: true